### ISSUE TITLE
Affiliate API still live?

### ISSUE THREAD

**Issue by ericaltendorf** [CoderJoshDK/WIOpy#5]
Not really a code issue, but since this repo is the only place I've been able to find on the internet where it looks like someone's been successfully using the affiliate API since after 2019...

Does anyone know if the API is it still live / supported?  Are there any secret hidden docs or guides or frontends?  All the docs, examples, and tools at walmart.io seem super bitrotted and broken, and I've tried multiple "application" entries with multiple client implementations (including this one) and I never get anything but a 401.

**Comment by ericaltendorf** [comment]
FWIW, I did manage to get the client working, and I also heard back from the walmart-IO support team when I had questions.  Their support is actually fairly helpful, despite the whole access portal looking like it hasn't been touched in years.

**Comment by CoderJoshDK** [comment]
Sorry I didn't get back to you in time. But glad you were able to get help! Yea, their site is a mess. It was why there is as much documentation here as there is. To (try) to let you avoid needing to go to their site as much as possible. 
I have tried to let them know of issues in the past. They just told me "thank you for letting us know. We will look into it and get back to you". They never got back to me. And at this point, I no longer need the API, so I don't have a strong reason to persist they fix the errors. 
That all being said, if you do find an error with my wrapper, please do let me know! PRs are very welcome. But even just making an issue, I will get to it! 

And thank you for using my repo! I am always glad to see other people getting use out of my code 😄.
